title: "Register to vote"
preamble: >
  <p>Register to vote to get on the electoral register, or to change your details. It usually takes about 5 minutes.</p>
  <p>You need to be on the electoral register to vote in general elections or referendums.</p>

faqs:
  - question: Deadline for registering to vote in the General Election
    answer: >
      <p>You can no longer register to vote in the General Election on 12 December. You can still register for future elections.</p>
      <p>If you’re already registered, you can still apply to <a href="/voting-in-the-uk?src=schema#voting-by-proxy">vote by proxy</a> in England, Scotland or Wales. Apply by 5pm on 4 December.</p>

  - question: Who can register
    answer: >
      <p>You can register if you’re both:</p>
      <ul>
        <li>aged 16 or over (or 14 or over in Scotland)</li>
        <li>a UK citizen (or an Irish, EU or Commonwealth citizen with a permanent UK address)</li>
      </ul>
      <p>You will not be able to vote until you’re 18. If you live in Scotland, you can vote in Scottish Parliament and local elections when you’re 16.</p>

  - question: Registering online
    answer: >
      <p>Use this service to get on the electoral register. You need to be on the electoral register to vote in elections and referendums.</p>
      <p>You only need to register once - not for every election.</p>
      <p><a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">Start now</a></p>
      <h2>What you need to know</h2>
      <p>You’ll be asked for your National Insurance number (but you can still register if you do not have one).</p>

  - question: How to check if you’re already registered
    answer: >
      <p>Contact your local Electoral Registration Office to <a href="/get-on-electoral-register?src=schema">find out if you’re already registered to vote</a>.</p>

  - question: Updating your registration
    answer: >
      <p>You can also use the <a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">‘Register to vote’ service</a> to:</p>
      <ul>
        <li>change your name, address or nationality</li>
        <li>get on or off the <a href="/electoral-register?src=schema">open register</a>
      </li>
      </ul>
      <p>To do this, you need to register again with your new details (even if you’re already registered to vote).</p>

  - question: Registering with a paper form
    answer: >
      <p>You can:</p>
      <ul>
        <li><a href="/government/publications/register-to-vote-if-youre-living-in-the-uk?src=schema">register using a paper form in England, Wales and Scotland</a></li>
        <li><a rel="external" href="http://www.eoni.org.uk/Register-To-Vote/Register-to-vote-change-address-change-name?src=schema">register using a paper form in Northern Ireland</a></li>
      </ul>

  - question: If you live abroad
    answer: >
      <p>You can use this service to <a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">apply to register to vote</a> (or to renew or update your registration) if you:</p>
      <ul>
        <li>are a British citizen</li>
        <li>left the UK within the last 15 years</li>
        <li>were previously registered at an address in England, Scotland or Wales (or, in some cases, you left the UK before your 18th birthday)</li>
      </ul>
      <p>You’ll need your passport details if you’re a British citizen living abroad, and want to vote in England, Scotland or Wales.</p>
      <p>If you previously lived in Northern Ireland and want to vote there, use the <a rel="external" href="http://www.eoni.org.uk/Register-To-Vote/Special-Category-Registration?src=schema">Northern Ireland overseas elector registration form</a>.</p>

  - question: If you’re a public servant posted overseas
    answer: >
      <p>There’s a different service for public servants (and their spouses and civil partners) who are posted overseas as:</p>
      <ul>
        <li><a href="/register-to-vote-crown-servants-british-council-employees?src=schema">Crown servants or British council employees</a></li>
        <li>members of the <a href="/register-to-vote-armed-forces?src=schema">armed forces</a>
      </li>
      </ul>

  - question: Get help registering
    answer: >
      <p>You can get help registering from your local <a href="/get-on-electoral-register?src=schema">Electoral Registration Office</a>.</p>
      <p>There’s an <a href="/government/publications/registering-to-vote-easy-read-guide?src=schema">easy read guide about registering to vote</a> for people with a learning disability.</p>
