version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: govuk*
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      - dependency-name: gds-api-adapters
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      - dependency-name: rails_translation_manager
        dependency-type: direct
      - dependency-name: slimmer
        dependency-type: direct
      # Framework gems
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: rspec-rails
        dependency-type: direct
      - dependency-name: jasmine
        dependency-type: direct
      - dependency-name: sassc-rails
        dependency-type: direct
      - dependency-name: pact
        dependency-type: direct
      - dependency-name: pact_broker-client
        dependency-type: direct

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      # Internal packages
      - dependency-name: stylelint-config-gds
        dependency-type: direct
      # Framework packages
      - dependency-name: standardx
        dependency-type: direct
      - dependency-name: stylelint
        dependency-type: direct

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ruby
