# This list taken from a combo of looking in
# https://github.com/alphagov/govuk-developer-docs/blob/main/data/rendering-apps.yml
# and finding the most popular example according to
# https://content-data.publishing.service.gov.uk/
---
answer: /national-minimum-wage-rates
calendar: /bank-holidays
call_for_evidence: /government/calls-for-evidence/credit-union-common-bond-reform
case-studies: /government/case-studies/doing-business-in-spain
consultation: /government/consultations/soft-drinks-industry-levy
corporate_information_page: /government/organisations/forensic-science-regulator/about
detailed_guide: /guidance/selling-second-hand-vehicles-using-a-vat-margin-scheme
document_collection: /government/collections/statutory-guidance-schools
fatality_notice: /government/fatalities/squadron-leader-patrick-marshall
field_of_operation: /government/fields-of-operation/united-kingdom
fields_of_operation: /government/fields-of-operation
get_involved: /government/get-involved
gone: /government/collections/greenhouse-gas-conversion-factors-for-company-reporting
guide: /log-in-register-hmrc-online-services
help_page: /help/browsers
history: /government/history/10-downing-street
html_publication: /government/publications/car-show-me-tell-me-vehicle-safety-questions/car-show-me-tell-me-vehicle-safety-questions
homepage: /
how_government_works: /government/how-government-works
licence_transaction: /find-licences/tv-licence
local_transaction: /contact-electoral-registration-office
manual: /guidance/the-highway-code
manual_section: /guidance/systems-change-learning/1-securing-strategic-buy-in-and-alignment
news_article: /government/news/the-personal-independence-payment-amendment-regulations-2017-statement-by-paul-gray
place: /find-regional-passport-office
publication: /government/publications/budget-2016-documents
service_manual_guide: /service-manual/agile-delivery/how-the-discovery-phase-works
service_manual_homepage: /service-manual
service_manual_service_standard: /service-manual/service-standard
service_manual_topic: /service-manual/helping-people-to-use-your-service
service_toolkit_page: /service-toolkit
simple_smart_answer: /sold-bought-vehicle
special-route: /find-local-council
specialist_document: https://content-data.publishing.service.gov.uk/
speeches: /government/speeches/motorcycle-testing
statistical_data_set: /government/statistical-data-sets/local-government-pension-scheme-funds-summary-data-2011-to-2012
statistics_announcement: /government/statistics/announcements/early-years-foundation-stage-profile-results-2024-to-2025
topical_event_about_page: /government/topical-events/western-balkans-summit-london-2018/about
transaction: /sign-in-universal-credit
travel_advice_index: /foreign-travel-advice
travel_advice: /foreign-travel-advice/azerbaijan
working_group: /government/groups/abstraction-reform
worldwide_office: /world/organisations/high-commission-victoria/office/british-high-commission-victoria
worldwide_organisation: /world/organisations/high-commission-victoria
