# This list taken from a combo of looking in
# https://github.com/alphagov/govuk-developer-docs/blob/main/data/rendering-apps.yml
# and finding the most popular example according to
# https://content-data.publishing.service.gov.uk/
---
calendar: /bank-holidays
licence_transaction: /find-licences/tv-licence
local_transaction: /contact-electoral-registration-office
help_page: /help/browsers
homepage: /
place: /find-regional-passport-office
simple_smart_answer: /sold-bought-vehicle
special-route: /find-local-council
transaction: /sign-in-universal-credit
travel_advice_index: /foreign-travel-advice
