services:
  1826:
    countries:
      unavailable_in:
        - Scotland
        - Northern Ireland
      content: |
        <p class="govuk-body">We've matched the postcode to <span class="local-authority">%{local_authority_name}</span>.</p>
        <p class="govuk-body">This service is not available in %{country_name}. You can find other services on the <span class="local-authority">%{local_authority_name}</span> website.</p>
  10001:
    countries:
      unavailable_in:
        - Scotland
        - Northern Ireland
        - Wales
      content: |
        <p class="govuk-body">We've matched the postcode to <span class="local-authority">%{local_authority_name}</span>.</p>
        <p class="govuk-body">This service is not available in %{country_name}. You can find other services on the <span class="local-authority">%{local_authority_name}</span> website.</p>
    local_authorities:
      content: |
        <p class="govuk-body">There are no rapid lateral flow test sites in this area yet. Check back later, or check your local council website for updates.</p>
        <p class="govuk-body">You may be able to get a rapid lateral flow test through your employer. If you have any of the following symptoms, you should get a PCR test for Covid-19 instead:</p>
